language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-19mode

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

env: CI="travis"

matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
      env: CI="travis"
    - rvm: 1.9.3
      jdk: oraclejdk8
      env: CI="travis"
    - rvm: 2.0.0
      jdk: openjdk7
      env: CI="travis"
    - rvm: 2.0.0
      jdk: oraclejdk8
      env: CI="travis"
    - rvm: 2.1
      jdk: openjdk7
      env: CI="travis"
    - rvm: 2.1
      jdk: oraclejdk8
      env: CI="travis"
